[package]
name = "advent_of_code_23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
lazy_static = "1.4.0"
rstest = "0.18.2"
thiserror = "1.0.50"
